language: node_js
sudo: false

node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "5"

script:
  - npm run lint
  - npm run test:ci

after_success:
  - npm install codecov
  - codecov

branches:
  only:
    - master
